applicationName: Legend SDLC

sessionCookie: LEGEND_SDLC_JSESSIONID

server:
  applicationConnectors:
    - type: http
      port: __LEGEND_SDLC_PORT__
      maxRequestHeaderSize: 128KiB
  adminConnectors:
    - type: http
      port: __LEGEND_SDLC_ADMIN_PORT__
  gzip:
    includedMethods:
      - GET
      - POST
  requestLog:
    type: classic
    level: OFF
    appenders:
      - type: console
        logFormat: "OFF"
  rootPath: /api

filterPriorities:
  GitLab: 1
  org.pac4j.j2e.filter.CallbackFilter: 2
  org.pac4j.j2e.filter.SecurityFilter: 3
  CORS: 4

pac4j:
  callbackPrefix: /api/pac4j/login
  mongoUri: mongodb://__MONGO_USER__:__MONGO_PASSWORD__@__MONGO_HOST__:__MONGO_PORT__
  mongoDb: legend
  clients:
    - org.finos.legend.server.pac4j.gitlab.GitlabClient:
        name: gitlab
        clientId: __GITLAB_OAUTH_CLIENT__
        secret: __GITLAB_OAUTH_SECRET__
        discoveryUri: https://gitlab.com/.well-known/openid-configuration
        scope: openid profile api
  mongoSession:
    enabled: true
    collection: userSessions
  bypassPaths:
    - /api/info

gitLab:
  newProjectVisibility: public
  projectIdPrefix: UAT
  projectTag: legend
  server:
    scheme: https
    host: gitlab.com
  app:
    id: __GITLAB_OAUTH_CLIENT__
    secret: __GITLAB_OAUTH_SECRET__
    redirectURI: __LEGEND_SDLC_URL__/api/auth/callback

features:
  canCreateProject: true
  canCreateVersion: true

projectStructure:
  projectCreation:
    groupIdPattern: ^com\.databricks\.legend\..+
  extensionProvider:
    org.finos.legend.sdlc.server.gitlab.finos.FinosGitlabProjectStructureExtensionProvider: {}
  platforms:
    legend-engine:
      groupId: org.finos.legend.engine
      version:
        12: __LEGEND_ENGINE_IMAGE_VERSION__
      platformVersion:
        version: __LEGEND_ENGINE_IMAGE_VERSION__
        fromPackage: legend-engine-protocol-pure
    legend-sdlc:
      groupId: org.finos.legend.engine
      version:
        12: __LEGEND_SDLC_IMAGE_VERSION__
      platformVersion:
        version: __LEGEND_SDLC_IMAGE_VERSION__
        fromPackage: legend-sdlc-server

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%thread] %c - %m%n"

swagger:
  resourcePackage: org.finos.legend.sdlc.server.resources
  title: Legend SDLC
  schemes: []