version: "3.8"
services:

  mongodb:
    container_name: $MONGO_SERVICE_NAME
    image: mongo:$MONGO_IMAGE_VERSION
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - legend
    env_file:
      - $BUILD_DIR/environment
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    command: --auth

  legend-sdlc:
    container_name: $LEGEND_SDLC_SERVICE_NAME
    image: finos/legend-sdlc-server:$LEGEND_SDLC_IMAGE_VERSION
    depends_on:
      - mongodb
    ports:
      - $LEGEND_SDLC_PORT:$LEGEND_SDLC_PORT
    networks:
      - legend
    volumes:
      - $BUILD_DIR/configs/sdlc:/config
      - $BUILD_DIR/scripts:/scripts
    env_file:
      - $BUILD_DIR/environment
    command: /scripts/run-sdlc.sh

  legend-engine:
    container_name: $LEGEND_ENGINE_SERVICE_NAME
    image: finos/legend-engine-server:$LEGEND_ENGINE_IMAGE_VERSION
    depends_on:
      - mongodb
    ports:
      - $LEGEND_ENGINE_PORT:$LEGEND_ENGINE_PORT
    networks:
      - legend
    volumes:
      - $BUILD_DIR/configs/engine:/config
      - $BUILD_DIR/scripts:/scripts
    env_file:
      - $BUILD_DIR/environment
    command: /scripts/run-engine.sh

  legend-studio:
    container_name: $LEGEND_STUDIO_SERVICE_NAME
    image: finos/legend-studio:$LEGEND_STUDIO_IMAGE_VERSION
    depends_on:
      - legend-sdlc
      - legend-engine
    ports:
      - $LEGEND_STUDIO_PORT:$LEGEND_STUDIO_PORT
    networks:
      - legend
    volumes:
      - $BUILD_DIR/configs/studio:/config
      - $BUILD_DIR/scripts:/scripts
    env_file:
      - $BUILD_DIR/environment
    command: /scripts/run-studio.sh

networks:
  legend: {}
